- name: Configure rating-update Service
  hosts: all
  remote_user: rnevils
  tasks:
    - name: Create quadlet config directory
      ansible.builtin.file:
        path: /home/rnevils/.config/containers/systemd
        state: directory
        mode: "0744"

    - name: Copy rating-update.container unit file
      ansible.builtin.copy:
        src: ./podman-systemd-service-units/rating-update.container
        dest: /home/rnevils/.config/containers/systemd/rating-update.container
        owner: rnevils
        group: rnevils
        mode: "0644"

    - name: Copy rating-update.pod unit file
      ansible.builtin.copy:
        src: ./podman-systemd-service-units/rating-update.pod
        dest: /home/rnevils/.config/containers/systemd/rating-update.pod
        owner: rnevils
        group: rnevils
        mode: "0644"

    - name: Restart rating-update service
      ansible.builtin.systemd_service:
        name: rating-update-pod.service
        scope: user
        state: restarted
        daemon_reload: true
        enabled: true
